In [1]:
from PyPDF2 import PdfReader

In [2]:
reader = PdfReader('./data/bank-statements/Bank Statement.pdf')

print(len(reader.pages))

page = reader.pages[0]

pdf_text = page.extract_text()
print(pdf_text)

1
1000 Walnut
Kansas City MO 64106-3686
Jane Customer
1234 Anywhere Dr.
Small Town, MO 12345-6789
Primary Account Number: 000009752
Bank Statement
If you have any questions about your statement, Statement Date:               June 5, 2003
please call us at 816-234-2265 Page Number:                                         1
CONNECTIONS CHECKING Account # 000009752
 Account Su mmary Account # 000009752
Beginning Balance on May 3, 2003                       $7,126.11
Deposits & Other Credits          +3,615.08
ATM Withdrawals & Debits                -20.00
VISA Check Card Purchases & Debits                  -0.00
Withdrawals & Other Debits       -0.00
Checks Paid              -200.00
          Ending Balance on June 5, 2003 $10,521.19
Deposits & Other Credits Account # 000009752
Description Date Credited                     Amount
Deposit Ref Nbr:     130012345                            05-15                                      $3,615.08
Total Deposits & Other Credits                    

In [3]:
# f = open("./data/.DS_Store","r")
# f

In [4]:
# import os
# if os.path.exists("./data/.DS_Store"):
#   os.remove("./data/.DS_Store")
# else:
#   print("The file does not exist")

In [5]:
import tensorflow as tf
from tensorflow import keras
import keras_ocr 
pipeline = keras_ocr.pipeline.Pipeline()

/Users/yashitabansal/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Looking for /Users/yashitabansal/.keras-ocr/craft_mlt_25k.h5
Instructions for updating:
Use `tf.image.resize(...method=ResizeMethod.BILINEAR...)` instead.
Looking for /Users/yashitabansal/.keras-ocr/crnn_kurapan.h5


In [6]:
images = [
    keras_ocr.tools.read(url) for url in [
        './data/address proof/address-proof-letter-for-employee_1.png',        
        'https://storage.googleapis.com/gcptutorials.com/examples/keras-ocr-img-2.png'
    ]
]

In [7]:
print(images[0])
print(images[1])    

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[242 232 163]
  [242 232 163]
  [242 232 163]
  ...
  [239 226 162]
  [239 226 161]
  [238 225 161]]

 [[242 232 163]
  [242 232 163]
  [242 232 163]
  ...
  [239 226 162]
  [238 225 161]
  [238 225 161]]

 [[242 232 163]
  [242 232 163]
  [242 232 163]
  ...
  [239 226 162]
  [238 225 161]
  [238 225 161]]

 ...

 [[217 230 204]
  [217 230 204]
  [217 230 204]
  ..

In [8]:
prediction_groups = pipeline.recognize(images)

5/5 [==============================] - 8s 1s/step


In [9]:
predicted_image_1 = prediction_groups[0]
image_text_list = []
for text, box in predicted_image_1:
    image_text_list.append(text)
image_text = " "
image_text = image_text.join(image_text_list)
print(image_text)

address proof letter for employee to whomsoever it may concern this is confim that is working in company to as designationy as the his services effective since date of record per company s were joiningl also would confimm address of name of the the employee want lo current as put the addresst employee records per company s as sincerely human resources your and your digital signaturel name address proof letter for employee to whomsoever it may concern this is confimm working company that is in o as efective designationy as the his services since date of record per company s were joiningl also would confim the address of name of the employce want to current put as address the employee records per company as s sincerely human resources signature your and your digital name appreciation letter candidateh dear name of the


In [10]:
# Tokenization On image
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(image_text)
image_tokens = [w for w in word_tokens if not w.lower() in stop_words]
print(image_tokens)

['address', 'proof', 'letter', 'employee', 'whomsoever', 'may', 'concern', 'confim', 'working', 'company', 'designationy', 'services', 'effective', 'since', 'date', 'record', 'per', 'company', 'joiningl', 'also', 'would', 'confimm', 'address', 'name', 'employee', 'want', 'lo', 'current', 'put', 'addresst', 'employee', 'records', 'per', 'company', 'sincerely', 'human', 'resources', 'digital', 'signaturel', 'name', 'address', 'proof', 'letter', 'employee', 'whomsoever', 'may', 'concern', 'confimm', 'working', 'company', 'efective', 'designationy', 'services', 'since', 'date', 'record', 'per', 'company', 'joiningl', 'also', 'would', 'confim', 'address', 'name', 'employce', 'want', 'current', 'put', 'address', 'employee', 'records', 'per', 'company', 'sincerely', 'human', 'resources', 'signature', 'digital', 'name', 'appreciation', 'letter', 'candidateh', 'dear', 'name']


In [11]:
# Tokenization On pdf
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(pdf_text)
pdf_tokens = [w for w in word_tokens if not w.lower() in stop_words]
print(pdf_tokens)

['1000', 'Walnut', 'Kansas', 'City', 'MO', '64106-3686', 'Jane', 'Customer', '1234', 'Anywhere', 'Dr.', 'Small', 'Town', ',', 'MO', '12345-6789', 'Primary', 'Account', 'Number', ':', '000009752', 'Bank', 'Statement', 'questions', 'statement', ',', 'Statement', 'Date', ':', 'June', '5', ',', '2003', 'please', 'call', 'us', '816-234-2265', 'Page', 'Number', ':', '1', 'CONNECTIONS', 'CHECKING', 'Account', '#', '000009752', 'Account', 'Su', 'mmary', 'Account', '#', '000009752', 'Beginning', 'Balance', 'May', '3', ',', '2003', '$', '7,126.11', 'Deposits', '&', 'Credits', '+3,615.08', 'ATM', 'Withdrawals', '&', 'Debits', '-20.00', 'VISA', 'Check', 'Card', 'Purchases', '&', 'Debits', '-0.00', 'Withdrawals', '&', 'Debits', '-0.00', 'Checks', 'Paid', '-200.00', 'Ending', 'Balance', 'June', '5', ',', '2003', '$', '10,521.19', 'Deposits', '&', 'Credits', 'Account', '#', '000009752', 'Description', 'Date', 'Credited', 'Amount', 'Deposit', 'Ref', 'Nbr', ':', '130012345', '05-15', '$', '3,615.08', '

In [12]:
feature_names = []

In [13]:
from spellchecker import SpellChecker
spell = SpellChecker()

def isPresent(token):
    digits = "0123456789.-,'()!:;+‘%$#@&^*|"
    present = 0
    for i in range(len(token)):
        if token[i] in digits:
            present = 1
            return True
    return False
 

def final_tokens(token_list):
    res = []
    list = token_list
    for token in list:
        token = str(token)
        if not isPresent(token):
            if spell.correction(token) == token:
                if token.lower() not in feature_names:
                    feature_names.append(token.lower())

                if token.lower() not in res:
                    res.append(token.lower())

    final__tokens = res

    return final__tokens

In [14]:
final_image_tokens = final_tokens(image_tokens)
print(final_image_tokens)

['address', 'proof', 'letter', 'employee', 'whomsoever', 'may', 'concern', 'working', 'company', 'services', 'effective', 'since', 'date', 'record', 'per', 'also', 'would', 'name', 'want', 'lo', 'current', 'put', 'records', 'sincerely', 'human', 'resources', 'digital', 'signature', 'appreciation', 'dear']


In [15]:
final_pdf_tokens = final_tokens(pdf_tokens)
print(final_pdf_tokens)

['walnut', 'kansas', 'city', 'mo', 'jane', 'customer', 'anywhere', 'small', 'town', 'primary', 'account', 'number', 'bank', 'statement', 'questions', 'date', 'june', 'please', 'call', 'us', 'page', 'connections', 'checking', 'su', 'beginning', 'balance', 'may', 'deposits', 'credits', 'atm', 'withdrawals', 'debits', 'visa', 'check', 'card', 'purchases', 'checks', 'paid', 'ending', 'description', 'credited', 'amount', 'deposit', 'ref', 'total', 'tran', 'withdrawal']


In [16]:
import os
target_labels = []
path_to_dataset = './data/'

In [17]:
for entry in os.scandir(path_to_dataset):
    if entry.is_dir():
        target_labels.append(entry.path[7:])

target_labels

['receipts',
 'power of attorney',
 'salary slip',
 'invoices',
 'bank-statements',
 'identity proof',
 'address proof',
 'personal finance statement',
 'tax return',
 'business proof',
 'fund raising',
 'employment proof']

In [18]:
def readPdf(file_path):
    input_pdf = open(file_path, 'rb')
    reader = PdfReader(input_pdf)
    page = reader.pages[0]
    pdf_text = page.extract_text()
    
    word_tokens = word_tokenize(pdf_text)
    pdf_tokens = [w for w in word_tokens if not w.lower() in stop_words]
    final_pdf_tokens = final_tokens(pdf_tokens)
    return final_pdf_tokens

In [19]:
def readImage(image_path):
#     input_image = Image.open(image_path)
    images = [keras_ocr.tools.read(image_path)]
    prediction_groups = pipeline.recognize(images)
    predicted_image_1 = prediction_groups[0]
    image_text_list = []
    for text, box in predicted_image_1:
        image_text_list.append(text)
    image_text = " "
    image_text = image_text.join(image_text_list)
    
    word_tokens = word_tokenize(image_text)
    image_tokens = [w for w in word_tokens if not w.lower() in stop_words]
    final_image_tokens = final_tokens(image_tokens)
    return final_image_tokens

In [24]:
for entry_in_dataset in os.scandir(path_to_dataset):
    for entry_in_file in os.scandir(entry_in_dataset):
        path_to_file = entry_in_file.path.replace('\\', '/')
        # now reading all dataset and adding the unique features into feature names
        if path_to_file[-4:] == '.pdf':
            #pdf input
            readPdf(path_to_file)
        elif path_to_file[-4:] == '.png' or path_to_file[-4:] == '.jpg':
            #image input
            readImage(path_to_file)

1/1 [==============================] - 11s 11s/step


3/3 [==============================] - 5s 1s/step


libpng warning: iCCP: extra compressed data


1/1 [==============================] - 10s 10s/step


1/1 [==============================] - 12s 12s/step


1/1 [==============================] - 11s 11s/step


5/5 [==============================] - 10s 2s/step


In [25]:
len(feature_names)

3659

In [49]:
feature_names.append('target_class')

'target_class'

In [ ]:
import pandas as pd
df = pd.DataFrame(columns = feature_names)

In [55]:
df

Empty DataFrame
Columns: [address, proof, letter, employee, whomsoever, may, concern, working, company, services, effective, since, date, record, per, also, would, name, want, lo, current, put, records, sincerely, human, resources, digital, signature, appreciation, dear, walnut, kansas, city, mo, jane, customer, anywhere, small, town, primary, account, number, bank, statement, questions, june, please, call, us, page, connections, checking, su, beginning, balance, deposits, credits, atm, withdrawals, debits, visa, check, card, purchases, checks, paid, ending, description, credited, amount, deposit, ref, total, tran, withdrawal, store, somewhere, ia, ford, fe, standard, phantom, oe, ca, tox, te, cee, charge, aids, codes, reduce, sone, ions, value, refund, ne, need, chance, enter, quick, ...]
Index: []

[0 rows x 3660 columns]

In [58]:
for entry_in_dataset in os.scandir(path_to_dataset):
    if entry_in_dataset.is_dir():
        className = entry_in_dataset.path[7:]
        print(className)
    for entry_in_file in os.scandir(entry_in_dataset):
        path_to_file = entry_in_file.path.replace('\\', '/')
        # now reading all dataset and adding the unique features into feature names
        if path_to_file[-4:] == '.pdf':
            #pdf input
            final_pdf_tokens = readPdf(path_to_file)
            row_for_df = [0] * len(feature_names)
            
            for i in range(len(feature_names)-1):
                if feature_names[i] in final_pdf_tokens:
                    row_for_df[i] = 1
            row_for_df[-1] = className
            df.loc[len(df.index)] = row_for_df
        elif path_to_file[-4:] == '.png' or path_to_file[-4:] == '.jpg':
            #image input
            final_image_tokens = readImage(path_to_file)
            row_for_df = [0] * len(feature_names)
            
            for i in range(len(feature_names)-1):
                if feature_names[i] in final_image_tokens:
                    row_for_df[i] = 1
            row_for_df[-1] = className
            df.loc[len(df.index)] = row_for_df

receipts
4/4 [==============================] - 6s 2s/step


4/4 [==============================] - 7s 2s/step
power of attorney
7/7 [==============================] - 11s 1s/step
salary slip
3/3 [==============================] - 4s 1s/step


libpng warning: iCCP: extra compressed data


4/4 [==============================] - 5s 1s/step
invoices
4/4 [==============================] - 6s 2s/step


4/4 [==============================] - 6s 1s/step
bank-statements
10/10 [==============================] - 17s 2s/step


10/10 [==============================] - 72s 8s/step
identity proof
2/2 [==============================] - 3s 1s/step
address proof
14/14 [==============================] - 22s 2s/step
personal finance statement
tax return
5/5 [==============================] - 6s 1s/step


8/8 [==============================] - 13s 2s/step
business proof
8/8 [==============================] - 16s 2s/step
fund raising
4/4 [==============================] - 7s 2s/step
employment proof
5/5 [==============================] - 10s 2s/step


In [59]:
df.shape

(422, 3660)

In [64]:
df.head()

address  proof  letter  employee  whomsoever  may  concern  working  \
0        0      0       0         0           0    1        0        0   
1        0      0       0         0           0    0        0        0   
2        0      0       0         0           0    1        0        0   

   company  services  ...  brooklyn  hanks  ofjune  quality  analyst  really  \
0        0         0  ...         0      0       0        0        0       0   
1        0         0  ...         0      0       0        0        0       0   
2        0         0  ...         0      0       0        0        0       0   

   great  lisa  marie  target_class  
0      0     0      0      receipts  
1      0     0      0      receipts  
2      0     0      0      receipts  

[3 rows x 3660 columns]

In [63]:
df.to_csv('data.csv', index=False)